version: "3"

services:
  ultra_backend_srv:
    env_file: ./.env
    container_name: ultra_api
    build: ./
    links:
      - ultra_database_srv
    depends_on:
      - ultra_database_srv
    volumes:
      - '.:/home/ultra-api'
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"

  ultra_database_srv:
    container_name: ultra_db
    image: postgres:latest
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    volumes:
      - ultra_database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}

volumes:
  ultra_database_volume:
